if(NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    option(VOX_ENABLE_CLANG_TIDY "Enable clang-tidy during compilation" ON)

    if(VOX_ENABLE_CLANG_TIDY)
        find_program(CLANGTIDY clang-tidy)

        if(CLANGTIDY)
            message(STATUS "Using clang-tidy")
            set(CMAKE_CXX_CLANG_TIDY "${CLANGTIDY};-extra-arg=-Wno-unknown-warning-option")

            if(WIN32)
                set(CMAKE_CXX_CLANG_TIDY "${CLANGTIDY};--extra-arg=/EHsc")
            endif()
        else()
            message(WARNING "clang-tidy requested but executable not found")
        endif()
    else()
        message(STATUS "clang-tidy integration disabled")
    endif()

    if(NOT WIN32)
        message(STATUS "Using address sanitizer")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -g -fsanitize=address")
    endif()
endif()
